# my file docker compose

services:
  mysql:
    image: mysql:latest
    container_name: mysql_laravel_enviroment
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: tdl
    ports:
      - 3306:3306
    volumes:
      - db_datas:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      # test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root --password= || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 90s

  tdl-api:
    build:
      context: ./tdlApi
      dockerfile: Dockerfile
    container_name: tdl-api
    ports:
      - 8080:8080
    restart: always
    extra_hosts:
      - "tdl-api.local=127.0.0.1"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s

  tdl:
    build:
      context: ./tdl
      dockerfile: Dockerfile
    container_name: tdl
    ports:
      - 8000:8000
    
    depends_on:
      mysql:
        condition: service_healthy
      tdl-api:
        condition: service_healthy
    restart: always
    extra_hosts:
      - "tdl.test=127.0.0.1"    


volumes:
  db_datas: