# my file docker compose

services:
  mysql:
    image: mysql:latest
    container_name: mysql_laravel_enviroment
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    volumes:
      - 'sail-mysql:/var/lib/mysql'
      - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
    restart: always
    healthcheck:
      # test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      # test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root --password= || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 90s

  tdl-api:
    build:
      context: ./tdlApi
      dockerfile: Dockerfile
    container_name: tdl-api
    ports:
      - 8080:8080
    restart: always
    extra_hosts:
      - "tdl-api.local=127.0.0.1"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s

  tdl:
    build:
      context: ./tdl
      dockerfile: Dockerfile
    container_name: tdl
    ports:
      - 8000:8000
    
    depends_on:
      mysql:
        condition: service_healthy
      tdl-api:
        condition: service_healthy
    restart: always
    extra_hosts:
      - "tdl.test=127.0.0.1"    


volumes:
  db_datas: